import json
import uuid
from pathlib import Path

class SlitherParser:
  """
  Class for parsing Slither analysis reports and normalizing the output
  into a structured list of finding dictionaries.
  """

  def parse_report(self, report, output_path="parsed_output.json"):
    """
    Parse the JSON report generated by Slither, normalize each detector finding,
    and write the normalized output to the specified file.

    Args:
      report (dict): The JSON object loaded from Slither's output.
      output_path (str, optional): Where to write the normalized findings.

    Returns:
      list: List of normalized detector findings.
    """
    # Get the list of detectors from the nested results
    detectors = report.get("results", {}).get("detectors", [])

    # Normalize each detector finding
    normalized = [self._normalize_detector(detector) for detector in detectors]
    # Save the normalized findings to disk as pretty-printed JSON
    Path(output_path).write_text(json.dumps(normalized, indent=2))
    return normalized

  def _normalize_detector(self, detector):
    """
    Normalize a single detector finding from the Slither report.

    Args:
      detector (dict): The detector entry from the Slither result.

    Returns:
      dict: A structured finding containing selected fields.
    """
    # Extract contract and function (if available) and code location
    elements = detector.get("elements", [])
    contract, function_name = self._extract_contract_and_function(elements)
    location = self._extract_location(elements)
    check_type = detector.get("check", "")

    # Construct normalized finding dictionary
    return {
      "id": str(uuid.uuid4()),  # Generate a unique identifier for this finding
      "tool": "slither",  # Hardcoded tool name
      "check_type": check_type,
      "severity": detector.get("impact", "").lower(),
      "confidence": detector.get("confidence", "").lower(),
      "contract": contract,
      "function": function_name,
      "location": location,
      "description": detector.get("description", "").strip(),
      "raw_tool_output": detector,  # Store full original detector result
      "invariant_category": "",     # Placeholder, not parsed here
      "verified": False,            # Default value (not verified)
    }

  def _extract_contract_and_function(self, elements):
    """
    Extract the contract name and function name from the detector elements.

    Args:
      elements (list): The list of annotated nodes from the detector finding.

    Returns:
      tuple: (contract_name, function_name)
    """
    contract = ""
    function_name = ""

    # Walk all nodes (recursive search) to find one contract and one function name
    for node in self._walk_nodes(elements):
      node_type = node.get("type")
      node_name = node.get("name")
      if node_type == "contract" and not contract and node_name:
        contract = node_name
      if node_type == "function" and not function_name and node_name:
        function_name = node_name
      if contract and function_name:
        break  # Stop early if both found

    return contract, function_name

  def _extract_location(self, elements):
    """
    Extract the first available source location from detector elements.

    Args:
      elements (list): The list of annotated nodes.

    Returns:
      dict: Dictionary with file, line_start, line_end.
    """
    for node in self._walk_nodes(elements):
      source_mapping = node.get("source_mapping")
      if not isinstance(source_mapping, dict):
        continue

      lines = source_mapping.get("lines") or []
      if not lines:
        continue

      # Prioritize relative file, then short, then absolute
      return {
        "file": (
          source_mapping.get("filename_relative")
          or source_mapping.get("filename_short")
          or source_mapping.get("filename_absolute")
          or ""
        ),
        "line_start": min(lines),
        "line_end": max(lines),
      }

    # Fallback if no source mapping is found
    return {"file": "", "line_start": None, "line_end": None}

  def _walk_nodes(self, value):
    """
    Recursively walk a nested structure (list or dict) of Slither output to yield all nodes.

    Args:
      value (any): Arbitrary nested JSON-compatible Python objects.

    Yields:
      dict: Every dictionary node found in the structure.
    """
    if isinstance(value, dict):
      yield value
      for nested in value.values():
        yield from self._walk_nodes(nested)
    elif isinstance(value, list):
      for item in value:
        yield from self._walk_nodes(item)
